"""Shared API and protocol limits.

These values describe stable request/resource contracts. Deployment-tunable
limits belong in :mod:`app.core.config` and are not duplicated here.
"""

MIN_PASSWORD_LENGTH = 6
MAX_PASSWORD_LENGTH = 256
MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 80

MAX_RESOURCE_NAME_LENGTH = 120
MAX_CONVERSATION_TITLE_LENGTH = MAX_RESOURCE_NAME_LENGTH
MAX_DISPLAY_NAME_LENGTH = MAX_RESOURCE_NAME_LENGTH
MAX_PROMPT_LENGTH = 100_000
MAX_KNOWLEDGE_SCOPES = 20
MAX_DOCUMENTS_PER_SCOPE = 100
MAX_ATTACHMENT_ID_LENGTH = 36
MAX_CHAT_BLOCK_ID_LENGTH = MAX_ATTACHMENT_ID_LENGTH
MAX_ETAG_LENGTH = 256

MAX_ATTACHMENTS_PER_MESSAGE = 10

DEFAULT_OBJECT_STORE_MAX_READ_BYTES = 32 * 1024 * 1024
DEFAULT_ATTACHMENT_MAX_BYTES = 20 * 1024 * 1024
DEFAULT_ATTACHMENT_MAX_PARSED_CHARS = 1_000_000
DEFAULT_ATTACHMENT_MAX_DECOMPRESSED_BYTES = 32 * 1024 * 1024
DEFAULT_ATTACHMENT_MAX_PDF_PAGES = 500
MAX_AGENT_HOME_FILE_CONTENT_BYTES = 1_000_000
DEFAULT_AGENT_HOME_MAX_FILE_BYTES = MAX_AGENT_HOME_FILE_CONTENT_BYTES
DEFAULT_KNOWLEDGE_DOCUMENT_MAX_BYTES = 20 * 1024 * 1024
DEFAULT_KNOWLEDGE_MAX_PARSED_CHARS = 2_000_000
DEFAULT_KNOWLEDGE_MAX_DECOMPRESSED_BYTES = 64 * 1024 * 1024
DEFAULT_KNOWLEDGE_MAX_PDF_PAGES = 1_000
DEFAULT_KNOWLEDGE_WORKER_PROCESSING_TIMEOUT_SECONDS = 300
DEFAULT_KNOWLEDGE_WORKER_POLL_INTERVAL_SECONDS = 1.0
# The runtime counter deliberately uses a conservative UTF-8 upper bound. Keep
# enough headroom for normal Chinese conversations plus capability tool schemas
# and tool-result reservations before pruning older turns.
DEFAULT_CHAT_CONTEXT_TOKEN_BUDGET = 32_000
DEFAULT_TOOL_RESULT_TOKEN_RESERVE = 4_096
DEFAULT_IMAGE_INPUT_TOKEN_RESERVE = 4_096
DEFAULT_MODEL_REQUEST_TIMEOUT_SECONDS = 30.0

MAX_KNOWLEDGE_COLLECTION_NAME_LENGTH = MAX_RESOURCE_NAME_LENGTH
DEFAULT_KNOWLEDGE_CHUNK_SIZE = 900
MIN_KNOWLEDGE_CHUNK_SIZE = 200
MAX_KNOWLEDGE_CHUNK_SIZE = 4_000
DEFAULT_KNOWLEDGE_CHUNK_OVERLAP = 120
MIN_KNOWLEDGE_CHUNK_OVERLAP = 0
MAX_KNOWLEDGE_CHUNK_OVERLAP = 1_000
DEFAULT_KNOWLEDGE_TOP_K = 5
MIN_KNOWLEDGE_TOP_K = 1
MAX_KNOWLEDGE_TOP_K = 10
MIN_KNOWLEDGE_SCORE_THRESHOLD = 0.0
MAX_KNOWLEDGE_SCORE_THRESHOLD = 1.0
DEFAULT_KNOWLEDGE_SCORE_THRESHOLD = 0.5
DEFAULT_KNOWLEDGE_VECTOR_WEIGHT = 0.7
DEFAULT_KNOWLEDGE_KEYWORD_WEIGHT = 0.3

DEFAULT_KNOWLEDGE_MAX_RESULTS = MAX_KNOWLEDGE_TOP_K
DEFAULT_KNOWLEDGE_MAX_QUERY_CHARS = 2_000
MAX_KNOWLEDGE_QUERY_CHARS = 20_000

DEFAULT_RUNTIME_MAX_TOOL_ROUNDS = 8
MAX_RUNTIME_MAX_TOOL_ROUNDS = 16

MAX_PROVIDER_TOKEN_COUNT = 2**63 - 1
